### ISSUE TITLE
Question: Could this be extended to support fonts?

### ISSUE THREAD

**Issue by stramec** [L-Blondy/tw-colors#1]
Hi there

Just stumbled across this plugin and wanted to say thanks, has saved me a heap of time on providing switchable themes on the my site.

I appreciate that this is aimed specifically at switching colours, but I wondered if you had any insights on if it is possible to extend the plugin to switch base font families as well. 

Any thoughts / ideas greatly appreciated.

Thanks one again!

**Comment by L-Blondy** [comment]
Hi Stewart, sorry for the late answer,

You can change anything thanks to variants, however it is not possible to
do so directly in the config at the moment.

To do so, first define the fonts in your tailwind config


module.exports = {
  theme: {
    fontFamily: {
      'roboto': ['roboto'],
      'calibri': ['calibri'],
      'rubik': ['rubik'],
    }
  }
}

Then switch them like that:

<html class="theme-light:font-roboto theme-dark:font-calibri
theme-halloween:font-rubik" >

Hope that helps!

Il mer 25 gen 2023, 04:58 Stewart McEwen ***@***.***> ha
scritto:

**Comment by L-Blondy** [comment]
Hi Stewart, sorry for the late answer,

You can change anything thanks to variants, however it is not possible to
do so directly in the config at the moment.

To do so, first define the fonts in your tailwind config

```
module.exports = {
  theme: {
    fontFamily: {
      'roboto': ['roboto'],
      'calibri': ['calibri'],
      'rubik': ['rubik'],
    }
  }
}
```

Then switch them like that:

```
<html class="theme-light:font-roboto theme-dark:font-calibri
theme-halloween:font-rubik" >
```

Hope that helps!

**Comment by tderkert** [comment]
I thought about this too, it feels like this concept could apply to pretty much all config properties and be a general theming engine. The suggested work-around is kind of something in between the current Tailwind approach and a more centralized theming system.

**Comment by stramec** [comment]
Thanks @L-Blondy - that worked great. I'm using a rails app and it wasn't happy with dynamically generating the classes, but once I hardcoded one for each them it worked like a charm! 

@tderkert - agreed this is an awesome plugin, lots of potential.

**Comment by mateuswolkmer** [comment]
Is there a currently way to achieve this globally? If not, I can help implementing if you think it fits the package @L-Blondy

**Comment by L-Blondy** [comment]
@mateuswolkmer 
I don't plan on supporting anything else than colors in the plugin's config. However if you look in the config there is a `resolveTwcConfig` export that you can use to create your own plugin. This way you get all the tw-colors features and you can add your own.

That said, here is how I would approach the spacing theming:

You can apply a multiplier variable to the spacing config
```
module.exports = {
  theme: {
    spacing: {
      '1': 'calc(var(--multiplier) * 0.25rem)',
      '2': 'calc(var(--multiplier) * 0.5rem)',
      '3': 'calc(var(--multiplier) * 0.75rem)',
      '4': 'calc(var(--multiplier) * 1rem )',
      ...    
    }
  }
}
```

And update the multiplier based on the theme with variants:

```
class='theme-1:[--multiplier:_1] theme-2:[--multiplier:_1.5] theme-3:[--multiplier:_2]'
```

Or with CSS

```
.theme-1 {
   --multiplier: 1;
}

.theme-2 {
   --multiplier: 1.5;
}

.theme-3 {
   --multiplier: 2;
}
```
