### ISSUE TITLE
Given a static return value, Color Decorators can be displayed

### ISSUE THREAD

**Issue by jipika** [L-Blondy/tw-colors#13]
![image](https://github.com/L-Blondy/tw-colors/assets/59040157/f3c221f0-f9bc-415b-a264-43ceee8adedd)
![image](https://github.com/L-Blondy/tw-colors/assets/59040157/808538d4-66fd-4fd9-85f5-881122d068c4)

Can you add this new feature ?

**Comment by L-Blondy** [comment]
> ![image](https://user-images.githubusercontent.com/59040157/239512764-f3c221f0-f9bc-415b-a264-43ceee8adedd.png) ![image](https://user-images.githubusercontent.com/59040157/239512891-808538d4-66fd-4fd9-85f5-881122d068c4.png)
> 
> Can you add this new feature ?

Could you be more specific about the use case ? I might be missing something here.
- Defining your colors using css variables defeats the purpose of this plugin
- static default values for CSS variables cannot be changed dynamically according to the theme by definition, therefore resulting in incorrect color decorators.

How would you configure tailwind + your CSS variables to make it a valid approach?

**Comment by jipika** [comment]
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/604
Refer to this link
That's enough
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      // ...
      colors: {
        primary: 'rgb(var(--primary, 66 66 66) / <alpha-value>)'
      }
    },
  },
  plugins: [],
}

**Comment by jipika** [comment]
Static return value to the css variable

**Comment by jipika** [comment]
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      // ...
      colors: {
        primary: 'rgb(var(--primary, 66 66 66) / <alpha-value>)'
      }
    },
  },
  plugins: [],
}

**Comment by jipika** [comment]
![image](https://github.com/L-Blondy/tw-colors/assets/59040157/c276f750-f4c8-48bd-9e19-bc7623f22bf5)

**Comment by jipika** [comment]
https://github.com/L-Blondy/tw-colors/pull/14
This submission has been fixed for this issue please view

**Comment by L-Blondy** [comment]
The default values, and therefore the color decorators correspond to the colors defined in the last theme of the config - in the case of your screenshot they correspond to the last theme.

As you are editing the classNames of the "light" theme, you get the color decorators of the "dark" theme, and always will.

An incorrect color decorator might be beneficial to some users, however it will be detrimental for many - if not most - users

**Comment by jipika** [comment]
This displays the dark return value when you need the dark theme and light when you need the light

**Comment by L-Blondy** [comment]
Nice idea but it might get nasty with nested themes. I'd rather wait for some automatic solution to be found.

Thanks anyways!

**Comment by dinwwwh** [comment]
I believe users should have the option to utilize this feature despite its incompatibility with nested and multiple themes. However, it still provides benefits. It's recommended to use the default theme.
