### ISSUE TITLE
how can use two different class one for dark and on for light in one element 

### ISSUE THREAD

**Issue by MOAB7698** [L-Blondy/tw-colors#19]
hi! 
how can use two different class one for dark and on for light in one element 
for example 
`    <hr class="border-primary-700  theme-light:border-red-200"  />
`
Because in some cases, in two different themes, the colors for one part may not be the same

**Comment by L-Blondy** [comment]
Is this what you need ?

`<hr class="theme-dark:border-primary-700  theme-light:border-red-200"  />`

Otherwise please share the following: config and minimalistic reproducible example
