### ISSUE TITLE
Hoisting CSS variables to root?

### ISSUE THREAD

**Issue by GreenImp** [L-Blondy/tw-colors#21]
Hi,

Is it possible to get the theme CSS variables set on the `:root` or `html`, rather than on the element that the theme is specified? I realise that this would break nested themes, but I was hoping to be able to pass through a flag so it can be turned on / off in the tailwind config. In my use case, I'm not nesting themes.

Maybe something like:

```javascript
plugins: [
    createThemes(
        {
            light: { 
                ...
            }
        },
        {
            // I'm useless at naming things..
            onRoot: true
        }
    )
],
```

My issue is that I need the variables accessible on the `html` and `body`, but I don't have access to the markup to add the theme declaration to them.

Instead, I have to add them to a HTML element inside the body, but this only makes them accessible inside that element.

**Comment by GreenImp** [comment]
Yes, that would be perfect!

**Comment by L-Blondy** [comment]
Add a `defaultTheme` option in version 2.1.0.

See https://github.com/L-Blondy/tw-colors#getcssvariable
