### ISSUE TITLE
make it work with class "light" instead of "theme-light"

### ISSUE THREAD

**Issue by hichemfantar** [L-Blondy/tw-colors#22]
Is it possible to make it work with the default tailwind light and dark classes?
I currently use `class="dark"` and `class="light"`

**Comment by L-Blondy** [comment]
Well, I could make the className prefix a configurable option, however having the theme className equal to the theme name would also result in the creation of the variants `light` and `dark` that would conflit with the dark variant of tailwind.

Bear in mind that with **tw-colors** you probably don't need to use variants at all if the only thing that change between a theme and another are the colors.

Can you provide a code sample (html or jsx) that shows what you are trying to achieve? This way I'll get a better idea of your issue

**Comment by L-Blondy** [comment]
Exposed a new `getThemeClassName` option in the latest version that lets you customize the theme classNames

**Comment by hichemfantar** [comment]
Thanks for the update, I haven't noticed your previous reply. I'll test and report.
