### ISSUE TITLE
tw-colors not working on nuxt's error.vue page , why ?

### ISSUE THREAD

**Issue by yazdanqm** [L-Blondy/tw-colors#23]
hello and thank you for the nice job

i used tw-colors in nuxt.js but it isn't work on error.vue page !

**Comment by MiladRST** [comment]
Yes, I have the same issue.

**Comment by L-Blondy** [comment]
False alarm?

**Comment by yazdanqm** [comment]
> False alarm?

that was my mistake , i should add data-theme in error.vue page of Nuxt
