### ISSUE TITLE
Variants without explicit theme declarations 

### ISSUE THREAD

**Issue by ninox14** [L-Blondy/tw-colors#24]
Request to make this happen 

Also is there a way to do this without declaring a theme on every component ?

**Comment by L-Blondy** [comment]
It would either break with nested themes or produce a huge amount of css. See [this thread](https://www.reddit.com/r/tailwindcss/comments/11aov92/comment/j9wf1zl/) for more details.

It would be interesting to see your use case for variants, can you share some code snippet?

**Comment by ninox14** [comment]
My potential use case is for UI components kit that has different themes  
```jsx
<html className="theme-two">
  <button className="rounded text-primary theme-two:rounded-lg theme-two:font-medium" />
</html>
```

**Comment by ninox14** [comment]
This could work but the config file would grow with the quantity of themes and components  
I feel like it would become a problem relatively fast

**Comment by L-Blondy** [comment]
If you really want that feature, **tw-colors** exposes the `resolveTwcConfig` for library authors. 

You can use it to resolve the colors, utilities and variants to inject into a custom plugin. 

```js
export const myCustomPlugin = (
   config = {},
   options = {},
) => {
   const resolved = resolveTwcConfig(config, options);

   return plugin(
      ({ addUtilities, addVariant }) => {
         // add the css variables to "@layer utilities"
         addUtilities(resolved.utilities);
         // This is how tw-colors injects the variants. 
         // You might omit this part, loop over your config to add your own variants
         // carefully check out the link in my first answer before proceeding, it contains somd warnings caveouts and example. 
         // Also check out the source code (lib/index.ts) to see the usage with Typescript
         resolved.variants.forEach(({ name, definition }) => addVariant(name, definition));
      },
      // extend the colors config
      {
         theme: {
            extend: {
               colors: resolved.colors,
            },
         },
      },
   );
};
```

**Comment by L-Blondy** [comment]
Added support for Variants without explicit theme declarations in v3.0.0
