### ISSUE TITLE
TWC color variables not set when using important mode in tailwind

### ISSUE THREAD

**Issue by useEffects** [L-Blondy/tw-colors#28]
![image](https://github.com/L-Blondy/tw-colors/assets/80976002/0ac6105f-fea1-4c1b-8341-8ad6d25a96b4)

**Comment by useEffects** [comment]
it works fine if i remove the important mode

**Comment by L-Blondy** [comment]
Hi @useEffects

Where do you declare the theme class (or data-theme), on a parent of `#__next :is(...)` or on a child?

Can you also share your tw-colors config in tailwind.config.js?

**Comment by useEffects** [comment]
Hii @L-Blondy thank you for quick response, its so dumb of me to include `data-theme` in the parent of `#__next`. Thank you for bringing this up and good luck. This is such a great repo for working with themes
