### ISSUE TITLE
rgba values loose opacity value

### ISSUE THREAD

**Issue by tderkert** [L-Blondy/tw-colors#3]
`foreground-500':  'rgba(255, 255, 255, 0.3)` in config turns into `.text-foreground-500
hsl(var(--twc-foreground-500) / var(--tw-text-opacity))` in the css class.

This color worked fine when it was in the regular part of the Tailwind color config.

**Comment by L-Blondy** [comment]
Fixed in version 1.0.8

**Comment by tderkert** [comment]
Thank you very much!  🙏
