### ISSUE TITLE
3.1.2 breaks my colors

### ISSUE THREAD

**Issue by AlanMorel** [L-Blondy/tw-colors#30]
Everything works on 3.1.1 but breaks on 3.1.2. I'm using Next.js and this is the relevant part of my tailwind.config.ts:

```typescript
import type { Config } from "tailwindcss";
import colors from "tailwindcss/colors";
import { createThemes } from "tw-colors";

const config: Config = {
    content: ["./app/**/*.{ts,tsx}", "./src/components/**/*.{ts,tsx}"],
    plugins: [
        createThemes({
            light: {
                white: colors.white,
                black: colors.black,
                slate: colors.slate
            },
            dark: {
                white: colors.black,
                black: colors.white,
                slate: colors.slate
            }
        })
    ],
};

export default config;
```

If I downgrade back to 3.1.1 without touching the code, everything works as intended again. I think the changes made to support [NativeWind](https://github.com/L-Blondy/tw-colors/commit/4208eeed2bffee6f4abde6d97f9bb1d7f630b7ad) in 3.1.2 is probably what broke it for me.

Thanks in advance for your work on this library!

**Comment by L-Blondy** [comment]
Hi @AlanMorel

Can you be more specific? What does not work?
Can you reproduce the issue in a miniml example?

**Comment by AlanMorel** [comment]
The thing that's "not working" is, for example, when I use `text-slate-900`, I see the color correctly on 3.1.1 but it's just black on 3.1.2.

This isn't a minimal example but it's small enough to illustrate the point (my personal portfolio site's [repo](https://github.com/AlanMorel/alanmorel.com)).

Steps to reproduce:
```
git clone https://github.com/AlanMorel/alanmorel.com
cd alanmorel.com
pnpm install
pnpm add tw-colors@3.1.1
pnpm dev
```

The colors and icons should look normal:
![chrome_tlCcnVgM7l](https://github.com/L-Blondy/tw-colors/assets/8239700/18d32b15-25ed-44f1-9daa-9fea8b9b7c19)

Now update to 3.1.2 and the same colors should now be black/white.

```
pnpm add tw-colors@3.1.2
pnpm dev
```

![chrome_JYBBxm2zA7](https://github.com/L-Blondy/tw-colors/assets/8239700/3b4ffa3a-faa9-4f9c-ac44-0b6cadf67ac1)

I tried downgrading back to Next.js 13 and on a different machine entirely but I'm still able to repeatedly break and fix the colors just by changing between these two versions.

**Comment by L-Blondy** [comment]
Found the issue, fixing it right now

**Comment by L-Blondy** [comment]
You can update to 3.2.0
