### ISSUE TITLE
Tailwind colors plugin defined colors don't work in portal

### ISSUE THREAD

**Issue by zeckdude** [L-Blondy/tw-colors#31]
Amazing plugin! Thank you!

When I use a portal and put content in there that uses a color that is defined using your plugin, the color variables won't work. Any ideas how I can get around that?

**Comment by L-Blondy** [comment]
Hi @zeckdude

It depends where you put your theme in the markup.
If your portal root is higher in the dom than the theme, then the theme variables do not exist yet.

The easiest fix might be to put the theme on the body or on the html tag

**Comment by zeckdude** [comment]
Hi @L-Blondy! Thanks for your quick reply. So it seems that everything works great in the portal on my website but the issue I am experiencing is in storybook. The funny thing is that normal tailwind classes work fine in or out of portals in storybook, but inside portals within storybook the tailwind classes still work but any classes created with the tw-colors plugin don't work because the css variables don't seem to be set. 

As far as how I have the tailwind styles being integrated into storybook, I am simply importing my globals.css file which has the `@tailwind base`, `@tailwind components`, and `@tailwind utilities` within it. 

Any ideas what I could still be missing?

**Comment by L-Blondy** [comment]
Did you wrap your stories with the theme?

**Comment by zeckdude** [comment]
I am familiar with decorators in storybook, but I'm uncertain what you mean by wrapping the stories with the theme. How do I wrap it with the theme?

**Comment by L-Blondy** [comment]
You should create a decorator to apply the theme.

The decorators itself wraps the stories by definition.

Now if your portal root is higher than the theme decorator the variables will again not exist, therefore you should set the root of the portall to an element under the theme

**Comment by zeckdude** [comment]
I'm just not sure what you mean by theme. For tailwind I just added it for my Next.js project and it works. I'm not really using any theme. But perhaps I'm misunderstanding you.

**Comment by L-Blondy** [comment]
`<div data-theme='light'>... </div>`

Thats what I mean

**Comment by zeckdude** [comment]
Ah I see. I've already been doing that. Here's my decorator:

```js
export const LightDarkThemeContainerDecorator = ({
  lightThemeContent,
  darkThemeContent,
  className,
  isScrollbarVisible = false,
}: {
  lightThemeContent: ReactNode
  darkThemeContent: ReactNode
  className?: string
  isScrollbarVisible?: boolean
}) => (
  <>
    <div
      className={twMerge(
        `flex justify-center py-16 bg-neutral-0 border border-information-500 mb-4 relative ${className}`,
      )}
      data-theme="light"
    >
      <div className="p-2 absolute top-0 left-0 bg-neutral-500">
        <Text variant={TextVariant.Xs} className="text-neutral-0">
          Light mode
        </Text>
      </div>
      <div className={clsx('mx-8', isScrollbarVisible && 'overflow-x-auto')}>
        {lightThemeContent}
      </div>
    </div>
    <div
      className={twMerge(
        `dark flex justify-center py-16 bg-neutral-700 border border-information-500 relative ${className}`,
      )}
      data-theme="dark"
      style={{ backgroundColor: '#12081D' }}
    >
      <div className="p-2 absolute top-0 left-0 bg-neutral-500">
        <Text variant={TextVariant.Xs} className="text-neutral-0">
          Dark mode
        </Text>
      </div>
      <div className={clsx('mx-8', isScrollbarVisible && 'overflow-x-auto')}>
        {darkThemeContent}
      </div>
    </div>
  </>
)
```

**Comment by L-Blondy** [comment]
Yep generally portals attach on the body, which sit higher than the decorator. Check out the documentation of the lib you use to customize it.

Otherwise last resort solution is to set the theme on the body or the html tag with a useEffect

**Comment by zeckdude** [comment]
That was a great idea! I made it so that when I click into one of my two themed containers, the body gets the same `data-theme` value so the portal has access. Thank you so much for your patience!

Btw, you have 0 open issues. That's truly amazing! Keep up the great work!
