### ISSUE TITLE
option to preserve hex values?

### ISSUE THREAD

**Issue by Numnumberry** [L-Blondy/tw-colors#33]
Hello! This is an awesome package.
I am curious why values are converted to HSL. When using the theme properties as variables, you have to do this:
```html
<body class='bg-[hsl(var(--custom-body))]'>
````
as opposed to this if it were to be a hex value:
```html
<body class='bg-[--custom-body]'>
```
Could there be an option to skip the HSL conversion? Or maybe an option to not store the raw HSL values, but store them already interpreted using `hsl()`

**Comment by L-Blondy** [comment]
Hi @Numnumberry 
Colors have to be converted to either hsl or rgb values in order to support opacity modifiers. Converting them to HEX would break many things since the following is not valid CSS:

```
.my-class {
    --my-color: #123456;
    color: var(--my-color)80;
}
```

a valid way is:

```
.my-class {
    --my-color: 0 100% 50%;
    color: hsl(var(--my-color) / 0.5);
}
```

or with rgb

```
.my-class {
    --my-color: 125 125 125;
    color: rgb(var(--my-color) / 0.5);
}
```

**Comment by maxkopych** [comment]
@L-Blondy We probably can use `color-mix` for that.  [Browser support](https://caniuse.com/?search=color-mix) for it not great but we getting there. 
It would be really nice to have hex support even with limitations.
