### ISSUE TITLE
color calculations result in different values than configured in theme

### ISSUE THREAD

**Issue by Jonnx** [L-Blondy/tw-colors#35]
I am running into a weird issue, likely caused by a potentially bad theme configuration:

```
brand1: {
    page: '#ffffff',
    section: '#f7f7f7',
    brand: {
        DEFAULT: '#0c4e19',
        '50': '#f0faeb',
        '100': '#dcf4d3',
        '200': '#bceaac',
        '300': '#92db7b',
        '400': '#6cca51',
        '500': '#4daf33',
        '600': '#388b25',
        '700': '#2d6b20',
        '800': '#0c4e19',
        '900': '#24491e',
        '950': '#0f270c',
    }
}
```

when using the `brand1` theme and an element with `bg-brand1` the effective color value used in the document is a few shades "dimmer":

expected value:
```
'#0c4e19
```

actual value:
```
#234c20
```

Any insight into what may be causing this would be much appreciated.

**Comment by L-Blondy** [comment]
Hi @Jonnx
Please share your tailwind.config.js file, the theme config you shared does not generate a brand1 color, therefore `bg-brand1` does not exist. You might have declared a brand1 color somewhere else in you config
