### ISSUE TITLE
how to assign color to scss variable?

### ISSUE THREAD

**Issue by costlydeveloper** [L-Blondy/tw-colors#37]
when colors are defined in standard way:

```
  theme: {
    extend: {
      colors: {
        gray: {
          50: '#f8f9fa',
          100: '#e9ecef',
          200: '#dee2e6',
          300: '#ced4da',
          400: '#adb5bd',
          500: '#6c757d',
          600: '#495057',
          700: '#343a40',
          800: '#212529',
          900: '#121212',
        },
      },
    },
```

we can assign color to scss variable in this way:
```
$shade200: theme('colors.gray.100');
```

but in this approach:
```
createThemes({
   'light': { 
      'primary': 'steelblue',
   },
   'dark': { 
      'primary': 'turquoise',
   },
}, {
   defaultTheme: 'light' // 'light' | 'dark'
})
```
if we try to add similar its not possible:

```
$shade200: theme('colors.primary');
```

**Comment by L-Blondy** [comment]
Try removing the apostrophe

`$shade200: theme(colors.primary);`

https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

**Comment by costlydeveloper** [comment]
hmmm not working without apostrophes either

![image](https://github.com/L-Blondy/tw-colors/assets/55545296/a2d0aa1b-c780-4e9e-8845-c01dd222552f)


but seems it works in this way:
$shade500: hsl(var(--twc-primary-900));

**Comment by costlydeveloper** [comment]
that is good enough in my case, it could be closed.

thank you for this great plugin.
