### ISSUE TITLE
How to install in Angular Framework

### ISSUE THREAD

**Issue by alfredotsco** [L-Blondy/tw-colors#4]
I tried to install it in my angular project with tailwindcss installed and I'm getting the following error:

Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Unable to parse color from string: at new Color (/app/node_modules/color/index.js:49:10) project | at Color (/app/node_modules/color/index.js:24:10) project | at /app/node_modules/tw-colors/dist/lib/index.js:52:70 project | at /app/node_modules/lodash.foreach/index.js:221:11 project | at baseForOwn (/app/node_modules/lodash.foreach/index.js:153:20) project | at /app/node_modules/lodash.foreach/index.js:190:14 project | at forEach (/app/node_modules/lodash.foreach/index.js:290:10) project | at /app/node_modules/tw-colors/dist/lib/index.js:48:38

**Comment by L-Blondy** [comment]
Hi, can you share your tailwind config?

**Comment by alfredotsco** [comment]
> Hi, can you share your tailwind config?

`const { createThemes } = require('tw-colors');

module.exports = {
  darkMode: 'media',
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    createThemes({
      light: {
        primary: "steelblue",
        secondary: "darkblue",
      },
      dark: {
        primary: "",
        secondary: ""
      }
    }),
  ],
}`

this is my tailwind config
