### ISSUE TITLE
Prefix option prevents CSS color variables generation in Tailwind CSS configuration

### ISSUE THREAD

**Issue by chipcop106** [L-Blondy/tw-colors#41]
I'm currently using Tailwind CSS v3.3.3 with the "tw-colors" plugin version v3.3.1. The default configuration setup still works correctly without using the prefix option in the tailwind.config.js file. However, when I attempt to add the prefix "zc-" to the prefix option, all CSS variables for colors are not generated; the color is missing.

Here is my configuration without the "zc-" prefix:
```js
module.exports = {
 dark modee: ['class'],
  content: [
    './src/**/*.{ts,tsx}',
  ],
 theme: {// some theme config},
  plugins: [createThemes(themeColor, {
    produceCssVariable: (colorName) => `--zc-${colorName}`,
  })],
};
```
With this configuration, all the CSS color variables are generated correctly:

<img width="283" alt="image" src="https://github.com/L-Blondy/tw-colors/assets/17249557/1781e627-1064-4c31-b3ee-17a4edd3f147">

After attempting to enable the prefix option with the value "zc-":

```js
module.exports = {
 dark modee: ['class'],
  content: [
    './src/**/*.{ts,tsx}',
  ],
 theme: {// some theme config},
 plugins: [createThemes(themeColor, {
    produceCssVariable: (colorName) => `--zc-${colorName}`,
  })],
 prefix: 'zc-'
};
```
The classes are generated correctly, but the CSS color variable --zc-gray-500 are not generated.

<img width="359" alt="image" src="https://github.com/L-Blondy/tw-colors/assets/17249557/89b1ef88-6bd0-42d0-9813-45041c1a89b9">

I'm working on my own UI library using TailwindCSS, and I want to add prefixes for all tailwind classes.

**Comment by L-Blondy** [comment]
Hi @chipcop106 
I reproduced your example and it all works fine:

```
module.exports = {
  darkMode: 'class',
  content: [ /* ... */ ],
  theme: { /* ... */ },
  prefix: 'zc-',
  plugins: [
    createThemes({
      light: { primary: 'red' },
      dark: { primary: 'blue' },
    }, {
      produceCssVariable: (colorName) => `--zc-${colorName}`,
    })
  ],

};
```

Keep in mind that:
1. the css variable are either declared on the <html> element (is case of default theme) or on the element where the theme is declared. In this case you will have access to the variable `--zc-primary` on the themed element and its children
2. you should then use tailwind classes with the prefix declared in the tailwind config object, for example `zc-bg-primary`

**Comment by chipcop106** [comment]
I have added "zc-light" in the HTML tag, and everything is working perfectly. Thanks for your help!
