### ISSUE TITLE
Broken typescript in tailwind.config.ts

### ISSUE THREAD

**Issue by ngdangtu-vn** [L-Blondy/tw-colors#44]
![image](https://github.com/user-attachments/assets/8af18286-564e-4995-89f7-3f9057097720)

```
Type '{ handler: PluginCreator; config?: Partial<Config> | undefined; }' is not assignable to type 'PluginCreator | { handler: PluginCreator; config?: Partial<Config>; } | { (options: any): { handler: PluginCreator; config?: Partial<...>; }; __isOptionsFunction: true; } | undefined'.
  Type '{ handler: PluginCreator; config?: Partial<Config> | undefined; }' is not assignable to type '{ handler: PluginCreator; config?: Partial<Config>; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    Types of property 'config' are incompatible.
      Type 'Partial<Config> | undefined' is not assignable to type 'Partial<Config>'.
        Type 'undefined' is not assignable to type 'Partial<Config>'.ts(2322)
```

Did I do something wrong?

**Comment by L-Blondy** [comment]
@ngdangtu-vn can you please share either
- a link to your repo or online sandbox
- or the following files: tailwind.config.ts, package.json, tsconfig.json

**Comment by ngdangtu-vn** [comment]
[tw-colors--i44.zip](https://github.com/user-attachments/files/16851759/tw-colors--i44.zip)

I've checked once more time today but the error is still there. While it is not serious as I can turn the type-checking off and continue my work, I thought I should share the case if there is anyone out there got the same problem.
