### ISSUE TITLE
How can I use css variables in my theme definitions?

### ISSUE THREAD

**Issue by felipeemarcon** [L-Blondy/tw-colors#45]
I'd like to use Tailwind colors, like `slate-900` in the definition of my themes. I should be able to do this using css variables? I'm not sure how can I handle this.

Heres an example:
```js
createThemes({
  light: {
    'content-high': "var(--slate-900)",
  },
  dark: {
    'content-high': "var(--slate-100)",
  }
}),
```

Or am I missing something?

**Comment by L-Blondy** [comment]
You can import tailwind color palette, no need for css variables

```ts
import colors from 'tailwindcss/colors'

...

createThemes({
  light: {
    'content-high': colors.slate.900,
  },
  dark: {
    'content-high': colors.slate.100,
  }
})
```

**Comment by felipeemarcon** [comment]
@L-Blondy thank you!
