### ISSUE TITLE
Theres a way to use theme variables in javascript files?

### ISSUE THREAD

**Issue by felipeemarcon** [L-Blondy/tw-colors#46]
I did not find how to use theme variables created by the plugin in a Javascript file. Could I achieve a result like this? For example:

tailwind.config.ts
```ts
...
plugins: [
  createThemes(
    {
      myTheme: {
        'brand': colors.red[500]
      },
      myTheme2: {
        'brand': colors.blue[500]
      }
    }
  ),
]
```

some-file.tsx
```tsx
<Component
  ...
  strokeColor={colors.brand}
  fillColor={colors.brand}
/>
```

Theres a way to do this consuming the definitions from my themes or am I trying to do something that I shouldn't, once that plugin sets the theme from classes and/or data-attribute? I'm not sure if I thinking straight here about that.

**Comment by L-Blondy** [comment]
There are css variables only, see the docs [here](https://github.com/L-Blondy/tw-colors?tab=readme-ov-file#css-variables)

Anyway you should use the class approach.
There are [stroke](https://tailwindcss.com/docs/stroke) and [fill](https://tailwindcss.com/docs/fill) utilities
