### ISSUE TITLE
How can I use the "dark:" variant?

### ISSUE THREAD

**Issue by mdelez** [L-Blondy/tw-colors#47]
First off, thank you for making this library as we find it quite useful. Something I can't seem to get working is the "dark:" variant. Here's a screenshot of my html. I'm trying to change the background of the button if I am in dark mode. The parent div has the class name to switch the themes. I've tried many different things but I can't get it to work. Any help would be appreciated!

<img width="1050" alt="Screenshot 2024-09-19 at 16 09 50" src="https://github.com/user-attachments/assets/d7134018-6892-42e1-a340-c0b9ebf1fe1b">

And here is my tailwind.config.js:

```
export default {
    content: ['./**/*.{js,ts,jsx,tsx,html}'],
    darkMode: ['selector', '[data-mode="dark"]'],
    important: true,
    theme: {
        extend: {
            maxWidth: {
                400: '400px'
            },
            padding: {
                '3px': '3px'
            },
            zIndex: {
                loading: zIndexes.loading
            }
        }
    },
    plugins: [
        createThemes({
            light: MyThemes.light,
            dark: MyThemes.dark
        })
    ],
    corePlugins: {
        preflight: false
    }
};
```

**Comment by L-Blondy** [comment]
I'm not familiar with MUI theming, but regarding tw-colors, you can simply remove the 'darkMode' option from your configuration, as tw-colors has built-in tools to manage it.

I'll close this issue for now
