### ISSUE TITLE
Colors in a tailwind preset get discarded

### ISSUE THREAD

**Issue by brunodavinci** [L-Blondy/tw-colors#49]
<img width="745" alt="demo" src="https://github.com/user-attachments/assets/0937c846-33e6-428d-bd93-c928460c48d0">

I've a preset defining some colors.
I use `tw-colors` to override some of these colors when a particular theme is enabled.
I can see correctly the new colors applied, but the colors that were originally in the preset, but not in the theme don't get applied.

I've setup a repo you can use to reproduce the issue:  [repro.zip](https://github.com/user-attachments/files/17342821/repro.zip).

Am i doing something wrong, or is this a problem in `tw-colors`? Thank you.

## Tailwind config

```js
const colors = {
  blue: "#00f",
  red: "#f00",
  orange: "#FFA500",
};

{
  content: ["./src/index.html"],
  theme: {
    extend: {},
  },
  presets: [
    {
      extend: {
        backgroundColor: {
          primary: colors.red,
          secondary: colors.blue,
        },
      },
    }
  ],
  plugins: [
    createThemes({
      demo: {
        primary: colors.orange,
      },
    }),
  ],
};
```

**Comment by L-Blondy** [comment]
With the following config (removing the plugin) can you see the secondary bg?

```
const colors = {
  blue: "#00f",
  red: "#f00",
  orange: "#FFA500",
};

{
  content: ["./src/index.html"],
  theme: {
    extend: {},
  },
  presets: [
    {
      extend: {
        backgroundColor: {
          primary: colors.red,
          secondary: colors.blue,
        },
      },
    }
  ],
  plugins: [],
};
```

**Comment by brunodavinci** [comment]
@L-Blondy This is what i get using the config you provided:

<img width="673" alt="image" src="https://github.com/user-attachments/assets/ba0b9c08-aabf-4a06-99ec-9f8831431725">

Basically, no background is applied.

**Comment by L-Blondy** [comment]
@brunodavinci the problem is with your preset. When using tw-colors the only color we see is the color of the plugin. Without using tw-colors we see no colors.

You should first make the preset colors work properly, then add tw-colors on top of it

**Comment by brunodavinci** [comment]
Mh, I see - thanks for the feedback @L-Blondy
