### ISSUE TITLE
Access primary colors of all themes

### ISSUE THREAD

**Issue by prokopec-simon** [L-Blondy/tw-colors#8]
Hey, first of all let me thank you for this great library, made implementing multiple color themes really easy. There is one thing I wanted to ask though.

Is there a way to obtain the css variables for primary colors of themes other than the currently being used? I want to implement a theme switcher where user sees examples of the primary colors and can pick one of them. The hsl(var(--twc-primary) variable works great for currently used theme, but I couldn't figure if I can obtain other themes this way too. Let's say something like --twc-dark-primary?

Thanks a lot and have a great day =)

**Comment by L-Blondy** [comment]
Hi Simon,

For a given color (let's say `primary`) only one CSS variable is generated, which changes color depending on the closest theme.

Therefore the only way to access the CSS variable value for a given theme is to use nested themes. 

In your case you probably don't need to access the variable at all, you might use the color directly. 

```html
<html class="theme-a">
	...

	<ul>
		<li class="theme-a bg-primary">
			theme-a primary preview
		</li>

		<li class="theme-b bg-primary">
			theme-b primary preview
		</li>

		<li class="theme-c bg-primary">
			theme-c primary preview
		</li>
	</ul>

	...
</html>
```

Hope that helps!

**Comment by prokopec-simon** [comment]
I should have probably left a little more info. I probably would actually need the css variables in my use case. It's a SvelteKit project and to switch the themes I use svg icons imported via [unplugin icons](https://github.com/antfu/unplugin-icons). Those come with a wrapper that, atleast to my knowledge, only accepts the actual color for their color attribute.

I couldn't override it manually or with Tailwind, atleast not easily. But it's not a huge deal. I'll probably just have the Theme colors statically defined somewhere.

**Comment by L-Blondy** [comment]
You might have a js/json file, import it in both tailwind.config.js and your theme switch component.

Note that you need esm support (tailwind >= 3.3.0) to do it with js files, otherwise you should go for json.

colors.js
```js
export const colors = {
    a: {
        primary: 'red'
    },
    b: {
        primary: 'blue'
    },
    c: {
        primary: 'yellow'
    },
}
```

tailwind.config.js
```js
import {colors} from '...'

export default {
      // ...your config
      plugins: [
         createThemes( colors )
      ],
   };
```

theme switcher
```js
import {colors} from '...'

console.log(colors)
```

**Comment by prokopec-simon** [comment]
Yeah, I've came up with something like this and it seems to do the job. Thanks a lot for the super fast and helpful assistance. If you ever need any form of help feel free to hit me up.
